# Environment Variables

$terminal = alacritty
$fileManager = nautilus
$menu = rofi -show drun -hover-select -theme ~/.config/rofi/launcher.rasi
$screenshot_area = hyprland-screenshot -m area -s off -l ~/Pictures/screenshots
$screenshot_window = hyprland-screenshot -m window -s off -l ~/Pictures/screenshots
$screenshot_all = hyprland-screenshot -m all -s off -l ~/Pictures/screenshots
$wlog = wlogout
$brave_browser = brave --password-store=basic
$zen_browser = zen-browser
$copyq = copyq show
$codeEditor = code
$eww_reload = eww reload
$waypaper = waypaper
$emoji_picker = smile

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Capitaine-Cursor-Gruvbox
env = GTK_THEME,Colloid-Dark-Gruvbox

env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = XDG_SESSION_TYPE,wayland

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto
