# --- Monitors ---
monitor=,highres,auto,1


# --- Sources ---
source = ~/.config/hypr/hyprstart.conf
source = ~/.config/hypr/hyprenvs.conf
source = ~/.config/hypr/hyprbinds.conf



# --- Look and Feel ---
general {
    gaps_in = 4
    gaps_out = 5
    border_size = 1

    col.active_border = rgba(458588ee)
    col.inactive_border = rgba(3c3836aa)

    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 4
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}

animations {
    enabled = yes, please :)

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 1.94, almostLinear, fade
    animation = workspacesIn, 1, 1.21, almostLinear, fade
    animation = workspacesOut, 1, 1.94, almostLinear, fade
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}


# --- Input ---
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

gestures {
    workspace_swipe = true
}

device {
    name = instant-usb-gaming-mouse-
    sensitivity = -0.15
    accel_profile = flat
}

device {
    name = elan0001:00-04f3:31ad-touchpad
    sensitivity = 0.3
    accel_profile = adaptive
}


# --- Windows and Workspaces ---
windowrulev2 = float, ^(org.pulseaudio.pavucontrol)$, title: ^(Volume Control)
windowrulev2 = size 700 400, title:^(Volume Control)$
windowrulev2 = float, class:^(blueman-manager)$, title: ^(Bluetooth Devices)$
windowrulev2 = workspace 3, class:^(Brave-browser)$
windowrule = float, ^(nm-connection-editor)$
windowrule = float, ^(Network)$
windowrule = float, ^(viewnior)$
windowrule = size 1024 768, ^(viewnior)$
windowrule = float, ^(com.github.hluk.copyq)$
windowrule = size 700 400, ^(com.github.hluk.copyq)$
windowrule = float, ^(org.gnome.Nautilus)$
windowrule = float, ^(stacer)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
