# Autostart apps and config

source = ~/.config/hypr/hyprenvs.conf

exec-once = alacritty
exec-once = blueman-applet --indicator
exec-once = sleep 2 && nm-applet --indicator
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DBUS_SESSION_BUS_ADDRESS HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = copyq
exec-once = swww-daemon
exec-once = swww img ~/Pictures/wallpapers/vagabond.png
exec-once = hypridle
exec = waybar
