# Autostart apps and config

source = ~/.config/hypr/hyprenvs.conf

exec-once = awww-daemon
# exec-once = swww img ~/Pictures/wallpapers/minimal.png

# exec-once = kitty
exec-once = blueman-applet &
exec-once = nm-applet --indicator &

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 & dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = copyq --start-server hide
exec-once = hypridle
exec-once = eww daemon
exec-once = eww open bar
